#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

from __future__ import absolute_import, division, print_function, unicode_literals

import os, sys, logging, pkgutil, importlib
import argcomplete
import aegea

logging.basicConfig(level=logging.INFO)
logging.getLogger("botocore.vendored.requests").setLevel(logging.ERROR)

for importer, modname, is_pkg in pkgutil.iter_modules(aegea.__path__):
    importlib.import_module((aegea.__package__ or "aegea") + "." + modname)

argcomplete.autocomplete(aegea.parser)

if len(sys.argv) < 2:
    aegea.parser.print_help()
    aegea.parser.exit(1)

args = aegea.parser.parse_args()
args.entry_point(args)
