#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

from __future__ import absolute_import, division, print_function, unicode_literals
from io import open

import os, sys, argparse, logging, socket, time, json, ipaddress, subprocess, zipfile, io, uuid, pkgutil, importlib
logging.basicConfig(level=logging.INFO)

import argcomplete

import aegea

for importer, modname, is_pkg in pkgutil.iter_modules(aegea.__path__):
    importlib.import_module((aegea.__package__ or "aegea") + "." + modname)

argcomplete.autocomplete(aegea.parser)
args = aegea.parser.parse_args()
args.entry_point(args)
